import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LocomotiveScrollProvider from '@/components/LocomotiveScrollProvider'
import Grain from '@/components/Grain'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Danny Green - Photography',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      <LocomotiveScrollProvider>
      {/* <Grain/> */}
        {children}
      </LocomotiveScrollProvider>
      </body>
    </html>
  )
}
